# Site settings
title: WebCastellum
email: denis@devtty.com
description: > # this means to ignore newlines until "baseurl:"
  WebCastellum WAF.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.webcastellum.org" # the base hostname & protocol for your site
twitter_username: dev_tty
github_username:  devtty

style: light

footer: 'footer'

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - index.md